/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.example1.form;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import rs.ac.bg.fon.silab.gui.example1.components.table.model.PorudzbinaTableModel;
import rs.ac.bg.fon.silab.gui.example1.controller.Controller;
import rs.ac.bg.fon.silab.gui.example1.session.Session;
import rs.ac.bg.fon.silab.jdbc.example1.domen.BillEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.BillItemlEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.CompanyEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.ProductEntity;

/**
 *
 * @author user
 */
public class FBill extends javax.swing.JDialog {

    /**
     * Creates new form FBill
     */
    public FBill(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBillTableModel();

        centerForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jtxtAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtCompany = new javax.swing.JTextField();
        jbtnSelectCompany = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblBillItems = new javax.swing.JTable();
        jbtnRemoveBillItem = new javax.swing.JButton();
        jbtnAddBillItem = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create new bill");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel3.setText("Amount");

        jtxtAmount.setEnabled(false);

        jLabel4.setText("Company");

        jtxtCompany.setEnabled(false);

        jbtnSelectCompany.setText("Select");
        jbtnSelectCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelectCompanyActionPerformed(evt);
            }
        });

        jtblBillItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblBillItems);

        jbtnRemoveBillItem.setText("-");
        jbtnRemoveBillItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveBillItemActionPerformed(evt);
            }
        });

        jbtnAddBillItem.setText("+");
        jbtnAddBillItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddBillItemActionPerformed(evt);
            }
        });

        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnAddBillItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnRemoveBillItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnSelectCompany))
                            .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSave)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSelectCompany))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbtnAddBillItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnRemoveBillItem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSave)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSelectCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelectCompanyActionPerformed
        JDialog selectCompanyForm = new FSelectCompany(null, true);
        selectCompanyForm.setVisible(true);
    }//GEN-LAST:event_jbtnSelectCompanyActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (Session.getInstance().getMap().containsKey("selected_company")) {
            CompanyEntity companyEntity = (CompanyEntity) Session.getInstance().getMap().get("selected_company");
            jtxtCompany.setText(companyEntity.getName() + ", " + companyEntity.getAddress());
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (Session.getInstance().getMap().containsKey("selected_company")) {
            Session.getInstance().getMap().remove("selected_company");
        }
    }//GEN-LAST:event_formWindowClosed

    private void jbtnAddBillItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddBillItemActionPerformed
        PorudzbinaTableModel btm = (PorudzbinaTableModel) jtblBillItems.getModel();
        btm.addNewBillItem();
//        jtxtAmount.setText(btm.getCurrentBillAmount() + "");
    }//GEN-LAST:event_jbtnAddBillItemActionPerformed

    private void jbtnRemoveBillItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveBillItemActionPerformed
        // TODO add your handling code here:
        int selectedItem = jtblBillItems.getSelectedRow();
        if (selectedItem >= 0) {
            PorudzbinaTableModel tableModel = (PorudzbinaTableModel) jtblBillItems.getModel();
            tableModel.removeItem(selectedItem);
//            jtxtAmount.setText(tableModel.getCurrentBillAmount() + "");
        }
    }//GEN-LAST:event_jbtnRemoveBillItemActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
        try {
            PorudzbinaTableModel btm = (PorudzbinaTableModel) jtblBillItems.getModel();
            BillEntity billEntity = btm.getBill();
            billEntity.setCreatedDate(LocalDate.now());
            billEntity.setCreatedTime(LocalTime.now());
            billEntity.setCreatedUser("N/A");
            if (Session.getInstance().getMap().containsKey("selected_company")) {
                billEntity.setCompanyEntity((CompanyEntity) 
                        Session.getInstance().getMap().get("selected_company")
                );
                Controller.saveBill(billEntity);
                JOptionPane.showMessageDialog(this, "Bill has been saved.");
            } else {
                throw new Exception("Please select company");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void centerForm() {
        setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAddBillItem;
    private javax.swing.JButton jbtnRemoveBillItem;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnSelectCompany;
    private javax.swing.JTable jtblBillItems;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtCompany;
    // End of variables declaration//GEN-END:variables

    private void setBillTableModel() {
        try {
            BillEntity bill = new BillEntity();
//        bill.setCreatedDate(LocalDate.now());
//        bill.setCreatedTime(LocalTime.now());

            TableModel billTableModel = new PorudzbinaTableModel(bill);
            jtblBillItems.setModel(billTableModel);

            List<ProductEntity> products = Controller.getAllProducts();
            JComboBox comboBox = new JComboBox(new DefaultComboBoxModel(products.toArray()));

            TableColumn columnProduct = jtblBillItems.getColumnModel().getColumn(1);
            columnProduct.setCellEditor(new DefaultCellEditor(comboBox));
        } catch (Exception ex) {
            Logger.getLogger(FBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
