/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.example1.form;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.silab.gui.example1.controller.Controller;
import rs.ac.bg.fon.silab.gui.example1.session.Session;
import rs.ac.bg.fon.silab.jdbc.example1.domen.IDomainEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.KupacEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.MestoEntity;

/**
 *
 * @author FON
 */
public class FMesto extends javax.swing.JDialog {

    /**
     * Creates new form FCompany
     */
    public FMesto(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        popuniComboZaMesto();
//        pripremiZaKreiranje();
//        centrirajFormu();
    }
    
    public FMesto(java.awt.Frame parent, boolean modal, String kupacJMBG) {
        super(parent, modal);
        initComponents();
//        popuniComboZaMesto();
//        pripremiZaPregled(kupacJMBG);
//        centrirajFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNaziv = new javax.swing.JLabel();
        jTxtNaziv = new javax.swing.JTextField();
        jLabelPTT = new javax.swing.JLabel();
        jTxtPTT = new javax.swing.JTextField();
        jBtnSacuvaj = new javax.swing.JButton();
        jBtnAzuriraj = new javax.swing.JButton();
        jBtnIzmeni = new javax.swing.JButton();
        jBtnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New company");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o mestu:"));

        jLabelNaziv.setText("Naziv:");

        jTxtNaziv.setText("a");
        jTxtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNazivActionPerformed(evt);
            }
        });

        jLabelPTT.setText("PTT: ");

        jTxtPTT.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNaziv)
                    .addComponent(jLabelPTT))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(jTxtPTT))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPTT)
                    .addComponent(jTxtPTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNaziv)
                    .addComponent(jTxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        jBtnSacuvaj.setText("Sacuvaj");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jBtnAzuriraj.setText("Azuriraj");
        jBtnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAzurirajActionPerformed(evt);
            }
        });

        jBtnIzmeni.setText("Izmeni");
        jBtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzmeniActionPerformed(evt);
            }
        });

        jBtnOtkazi.setText("Otkazi");
        jBtnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 458, Short.MAX_VALUE)
                        .addComponent(jBtnOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAzuriraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnIzmeni)
                        .addGap(1, 1, 1)
                        .addComponent(jBtnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSacuvaj)
                    .addComponent(jBtnAzuriraj)
                    .addComponent(jBtnIzmeni)
                    .addComponent(jBtnOtkazi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed
        try {
//            String jmbg = jTxtPTT.getText().trim();
//            String ime   = jTxtNaziv.getText().trim();
//            String prezime   = jTxtPrezime.getText().trim();
//            String dat = jTxtDatumRodj.getText().trim();
//            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
//            Date datumRodj = sdf.parse(dat);
//            String email = jTxtEmail.getText().trim();
//            String brTel = jTxtBrojTelefona.getText().trim();
//            String adresa = jTxtAdresa.getText().trim();
//            MestoEntity mesto = (MestoEntity) jComboMesto.getSelectedItem();
//            KupacEntity kupac = new KupacEntity(jmbg, ime, prezime, datumRodj, email, brTel, adresa, mesto);
//            System.out.println("AvA: "+kupac.toString());
////            kupac = Controller.sacuvajKupca(kupac);
//            kupac = (KupacEntity) Controller.sacuvaj(kupac);
//            JOptionPane.showMessageDialog(this, "Uspesno je sacuvan kupac!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Kupac nije uspesno sacuvan!");
        }
    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    private void jBtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzmeniActionPerformed
//        pripremiFormu(FormMode.IZMENA);
    }//GEN-LAST:event_jBtnIzmeniActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (Session.getInstance().getMap().containsKey("izabrano_mesto")) {
            MestoEntity mesto = (MestoEntity) Session.getInstance().getMap().get("izabrano_mesto");
//            jComboMesto.setSelectedItem(mesto);
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (Session.getInstance().getMap().containsKey("izabrano_mesto")){
            Session.getInstance().getMap().remove("izabrano_mesto");
            JOptionPane.showMessageDialog(null, "Uklanjanje izabranog grada iz sesije");
        }
    }//GEN-LAST:event_formWindowClosed

    private void jBtnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAzurirajActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "TODO: Implement this Use Case!");
    }//GEN-LAST:event_jBtnAzurirajActionPerformed

    private void jBtnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOtkaziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnOtkaziActionPerformed

    private void jTxtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNazivActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAzuriraj;
    private javax.swing.JButton jBtnIzmeni;
    private javax.swing.JButton jBtnOtkazi;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JLabel jLabelPTT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtNaziv;
    private javax.swing.JTextField jTxtPTT;
    // End of variables declaration//GEN-END:variables

//    private void popuniComboZaMesto() {
//        try {
//            jComboMesto.removeAllItems();
//            List<IDomainEntity> mesta = Controller.vratiSve(new MestoEntity());
//            
//            for (IDomainEntity mesto : mesta) {
//                if(mesto instanceof MestoEntity)
//                    jComboMesto.addItem((MestoEntity) mesto);
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(FMesto.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//    
//    private void pripremiZaPregled(String kupacJMBG) {
//        pripremiFormu(FormMode.PREGLED);
//        try {
//            KupacEntity kupac = Controller.nadjiKupcaPoJMBGu(kupacJMBG);
//            
//            setTitle("Pregled kupca: " + kupac.getImeKupca());
//            
//            jTxtPTT.setText(kupac.getJmbgKupca());
//            jTxtNaziv.setText(kupac.getImeKupca());
//            jTxtPrezime.setText(kupac.getPrezimeKupca());
//            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
//            String datumRodjenja = sdf.format(kupac.getDatumRodjenja());
//            jTxtDatumRodj.setText(datumRodjenja);
//            jTxtEmail.setText(kupac.getEmail());
//            jTxtBrojTelefona.setText(kupac.getBrojTelefona());
//            jTxtAdresa.setText(kupac.getAdresa());
//            jComboMesto.setSelectedItem(kupac.getMesto());
//        } catch (Exception ex) {
//            Logger.getLogger(FMesto.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//    
//    private void pripremiZaIzmenu() {
//        pripremiFormu(FormMode.IZMENA);
//    }
//    
//    private void pripremiZaKreiranje() {
//        pripremiFormu(FormMode.KREIRANJE);
//    }
//    
//    void pripremiFormu(FormMode mode) {
//        switch (mode) {
//            case IZMENA:
//                jBtnAzuriraj.setEnabled(true);
//                jBtnIzmeni.setEnabled(false);
//                jBtnSacuvaj.setEnabled(false);
//                jBtnOtkazi.setEnabled(false);
//                jBtnIzaberi.setEnabled(true);
//                
//                jTxtPTT.setVisible(true);
//                jLabelPTT.setVisible(true);
//                jLabelPTT.setEnabled(false);
//                
//                jComboMesto.setEnabled(true);
//                jTxtEmail.setEnabled(true);
//                jTxtPrezime.setEnabled(true);
//                jTxtNaziv.setEnabled(true);
//                jTxtDatumRodj.setEnabled(true);
//                jTxtAdresa.setEnabled(true);
//                jTxtBrojTelefona.setEnabled(true);
//                
//                break;
//            case KREIRANJE:
//                jBtnAzuriraj.setEnabled(false);
//                jBtnIzmeni.setEnabled(false);
//                jBtnSacuvaj.setEnabled(true);
//                jBtnOtkazi.setEnabled(false);
//                jBtnIzaberi.setEnabled(true);
//                
//                jTxtPTT.setVisible(true);
//                jLabelPTT.setVisible(true);
//                
//                jComboMesto.setEnabled(true);
//                jTxtEmail.setEnabled(true);
//                jTxtPrezime.setEnabled(true);
//                jTxtNaziv.setEnabled(true);
//                jTxtDatumRodj.setEnabled(true);
//                jTxtAdresa.setEnabled(true);
//                jTxtBrojTelefona.setEnabled(true);
//                
//                break;
//            case PREGLED:
//                jBtnAzuriraj.setEnabled(false);
//                
//                jBtnIzmeni.setEnabled(true);
//                jBtnSacuvaj.setEnabled(false);
//                jBtnOtkazi.setEnabled(false);
//                jBtnIzaberi.setEnabled(false);
//                
//                jTxtPTT.setVisible(true);
//                jLabelPTT.setVisible(true);
//                jTxtPTT.setEnabled(false);
//                
//                jComboMesto.setEnabled(false);
//                jTxtEmail.setEnabled(false);
//                jTxtPrezime.setEnabled(false);
//                jTxtNaziv.setEnabled(false);
//                jTxtDatumRodj.setEnabled(false);
//                jTxtAdresa.setEnabled(false);
//                jTxtBrojTelefona.setEnabled(false);
//                break;
//        }
//    }
//    
//    private void centrirajFormu() {
//        setLocationRelativeTo(null);
//    }
    
}
