/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.example1.form;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.silab.gui.example1.controller.Controller;
import rs.ac.bg.fon.silab.gui.example1.session.Session;
import rs.ac.bg.fon.silab.jdbc.example1.domen.IDomainEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.KupacEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.MestoEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.ProizvodEntity;
import rs.ac.bg.fon.silab.jdbc.example1.domen.TipProizvodaEntity;

/**
 *
 * @author FON
 */
public class FProizvod extends javax.swing.JDialog {
    ProizvodEntity proizvod;
    /**
     * Creates new form FCompany
     */
    public FProizvod(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniComboZaTipProizvoda();
        pripremiZaKreiranje();
        centrirajFormu();
    }
    
    public FProizvod(java.awt.Frame parent, boolean modal, Long proizvodID) {
        super(parent, modal);
        initComponents();
        popuniComboZaTipProizvoda();
        pripremiZaPregled(proizvodID);
        centrirajFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCena = new javax.swing.JLabel();
        jTxtCena = new javax.swing.JTextField();
        jLabelTip = new javax.swing.JLabel();
        jComboTipProizvoda = new javax.swing.JComboBox<>();
        jBtnIzaberi = new javax.swing.JButton();
        jLabelNaziv = new javax.swing.JLabel();
        jTxtNaziv = new javax.swing.JTextField();
        jBtnSacuvaj = new javax.swing.JButton();
        jBtnAzuriraj = new javax.swing.JButton();
        jBtnIzmeni = new javax.swing.JButton();
        jBtnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novi proizvod");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o proizvodu:"));

        jLabelCena.setText("Cena:");

        jTxtCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCenaActionPerformed(evt);
            }
        });

        jLabelTip.setText("Tip proizvoda:");

        jBtnIzaberi.setText("Izaberi");
        jBtnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzaberiActionPerformed(evt);
            }
        });

        jLabelNaziv.setText("Naziv:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCena)
                    .addComponent(jLabelTip)
                    .addComponent(jLabelNaziv))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtCena)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnIzaberi))
                    .addComponent(jTxtNaziv)
                    .addComponent(jComboTipProizvoda, 0, 497, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNaziv)
                    .addComponent(jTxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCena)
                    .addComponent(jTxtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnIzaberi)
                .addGap(92, 92, 92))
        );

        jBtnSacuvaj.setText("Sacuvaj");
        jBtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSacuvajActionPerformed(evt);
            }
        });

        jBtnAzuriraj.setText("Azuriraj");
        jBtnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAzurirajActionPerformed(evt);
            }
        });

        jBtnIzmeni.setText("Izmeni");
        jBtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzmeniActionPerformed(evt);
            }
        });

        jBtnOtkazi.setText("Otkazi");
        jBtnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 390, Short.MAX_VALUE)
                        .addComponent(jBtnOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAzuriraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnIzmeni)
                        .addGap(1, 1, 1)
                        .addComponent(jBtnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSacuvaj)
                    .addComponent(jBtnAzuriraj)
                    .addComponent(jBtnIzmeni)
                    .addComponent(jBtnOtkazi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSacuvajActionPerformed
        try {
            String naziv = jTxtNaziv.getText().trim();
            Double cena   = Double.parseDouble(jTxtCena.getText().trim());
            TipProizvodaEntity tipPr = (TipProizvodaEntity) jComboTipProizvoda.getSelectedItem();
            ProizvodEntity proizvod = new ProizvodEntity(naziv, cena, tipPr);
            proizvod = (ProizvodEntity) Controller.zapamtiProizvod(proizvod);
            JOptionPane.showMessageDialog(this, "Uspesno je sacuvan proizvod!");
            dispose();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Proizvod nije uspesno sacuvan!");
        }
    }//GEN-LAST:event_jBtnSacuvajActionPerformed

    private void jBtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzmeniActionPerformed
        pripremiFormu(FormMode.IZMENA);
    }//GEN-LAST:event_jBtnIzmeniActionPerformed

    private void jBtnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzaberiActionPerformed
        JDialog fIzaberiTip = new FIzaberiTipProizvoda(null, true);
        fIzaberiTip.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBtnIzaberiActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (Session.getInstance().getMap().containsKey("izabraniTipProizvoda")) {
            TipProizvodaEntity tip = (TipProizvodaEntity) Session.getInstance().getMap().get("izabraniTipProizvoda");
            jComboTipProizvoda.setSelectedItem(tip);
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (Session.getInstance().getMap().containsKey("izabraniTipProizvoda")){
            Session.getInstance().getMap().remove("izabraniTipProizvoda");
        }
    }//GEN-LAST:event_formWindowClosed

    private void jBtnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAzurirajActionPerformed
         try {
            String naziv = jTxtNaziv.getText().trim();
            Double cena = Double.parseDouble(jTxtCena.getText().trim());
            TipProizvodaEntity tip = (TipProizvodaEntity) jComboTipProizvoda.getSelectedItem();
            ProizvodEntity proizvod = new ProizvodEntity(this.proizvod.getIdProizvoda(),naziv, cena, tip);
            proizvod = (ProizvodEntity) Controller.izmeniProizvod(proizvod);
            JOptionPane.showMessageDialog(this, "Sistem je azurirao proizvod");
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da azurira proizvod");
            Logger.getLogger(FKupac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnAzurirajActionPerformed

    private void jBtnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOtkaziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnOtkaziActionPerformed

    private void jTxtCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAzuriraj;
    private javax.swing.JButton jBtnIzaberi;
    private javax.swing.JButton jBtnIzmeni;
    private javax.swing.JButton jBtnOtkazi;
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JComboBox<rs.ac.bg.fon.silab.jdbc.example1.domen.TipProizvodaEntity> jComboTipProizvoda;
    private javax.swing.JLabel jLabelCena;
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JLabel jLabelTip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCena;
    private javax.swing.JTextField jTxtNaziv;
    // End of variables declaration//GEN-END:variables

    private void popuniComboZaTipProizvoda() {
        try {
            jComboTipProizvoda.removeAllItems();
            List<TipProizvodaEntity> tipoviproizvoda = Controller.ucitajListuTipovaProizvoda();
            
            for (IDomainEntity tip : tipoviproizvoda) {
                if(tip instanceof TipProizvodaEntity)
                    jComboTipProizvoda.addItem((TipProizvodaEntity) tip);
            }
        } catch (Exception ex) {
            Logger.getLogger(FProizvod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void pripremiZaPregled(Long prID) {
        pripremiFormu(FormMode.PREGLED);
        try {
            System.out.println("aaaaaaaaaa");
            proizvod = Controller.nadjiProizvodPoIDu(prID);
            setTitle("Pregled proizvoda: " + proizvod.getNazivProizvoda());
            
            jTxtNaziv.setText(proizvod.getNazivProizvoda());
            jTxtCena.setText(proizvod.getCena().toString());
            jComboTipProizvoda.setSelectedItem(proizvod.getTipProizvoda());
        } catch (Exception ex) {
            Logger.getLogger(FKupac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void pripremiZaIzmenu() {
        pripremiFormu(FormMode.IZMENA);
    }
    
    private void pripremiZaKreiranje() {
        pripremiFormu(FormMode.KREIRANJE);
    }
    
    void pripremiFormu(FormMode mode) {
        switch (mode) {
            case IZMENA:
                jBtnAzuriraj.setEnabled(true);
                jBtnIzmeni.setEnabled(false);
                jBtnSacuvaj.setEnabled(false);
                jBtnOtkazi.setEnabled(false);
                jBtnIzaberi.setEnabled(true);
                
                jTxtNaziv.setVisible(true);
                jLabelNaziv.setVisible(true);
                jLabelNaziv.setEnabled(false);
                
                jComboTipProizvoda.setEnabled(true);
                jTxtCena.setEnabled(true);
                jTxtNaziv.setEnabled(true);
                
                break;
            case KREIRANJE:
                jBtnAzuriraj.setEnabled(false);
                jBtnIzmeni.setEnabled(false);
                jBtnSacuvaj.setEnabled(true);
                jBtnOtkazi.setEnabled(false);
                jBtnIzaberi.setEnabled(true);
                
                jTxtNaziv.setVisible(true);
                jLabelNaziv.setVisible(true);
                
                jComboTipProizvoda.setEnabled(true);
                jTxtCena.setEnabled(true);
                jTxtNaziv.setEnabled(true);
                
                break;
            case PREGLED:
                jBtnAzuriraj.setEnabled(false);
                
                jBtnIzmeni.setEnabled(true);
                jBtnSacuvaj.setEnabled(false);
                jBtnOtkazi.setEnabled(false);
                jBtnIzaberi.setEnabled(false);
                
                jTxtNaziv.setVisible(true);
                jLabelNaziv.setVisible(true);
                jTxtNaziv.setEnabled(false);
                jTxtNaziv.setDisabledTextColor(Color.DARK_GRAY);
                jTxtCena.setDisabledTextColor(Color.DARK_GRAY);
                
                jComboTipProizvoda.setEnabled(false);
                jTxtNaziv.setEnabled(false);
                jTxtCena.setEnabled(false);
                break;
        }
    }
    
    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }
    
}
