/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.silab.gui.example1.form;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import rs.ac.bg.fon.silab.gui.example1.components.table.model.KupacTableModel;
import rs.ac.bg.fon.silab.gui.example1.controller.Controller;
import rs.ac.bg.fon.silab.jdbc.example1.domen.CompanyEntity;

/**
 *
 * @author FON
 */
public class FSearchCompany extends javax.swing.JDialog {

    /**
     * Creates new form FSearchCompany
     */
    public FSearchCompany(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        populateTableCompanies();
        centerForm();
        setColumnSizeTableCompanies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCompanies = new javax.swing.JTable();
        jBtnView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search company");

        jTblCompanies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CompanyID", "Name", "Address", "Vat", "Ident number", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblCompanies);

        jBtnView.setText("View");
        jBtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnView)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnView)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViewActionPerformed
        int selectedRow = jTblCompanies.getSelectedRow();
        if (selectedRow >= 0) {
            Long companyId = (Long) jTblCompanies.getValueAt(selectedRow, 0);
            JOptionPane.showMessageDialog(null, "Selected company has ID: " + companyId);

            JDialog fCompany = new FKupac(null, true, companyId);
            fCompany.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a company!!!");
        }

    }//GEN-LAST:event_jBtnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCompanies;
    // End of variables declaration//GEN-END:variables

    private void populateTableCompanies() {
        try {
            List<CompanyEntity> companies = Controller.getAllCompanies();
            TableModel tm = new KupacTableModel(companies);
            jTblCompanies.setModel(tm);
        } catch (Exception ex) {
            Logger.getLogger(FSearchCompany.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void centerForm() {
        setLocationRelativeTo(null);
    }

    private void setColumnSizeTableCompanies() {        
        jTblCompanies.getColumnModel().getColumn(0).setPreferredWidth(27);
        jTblCompanies.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTblCompanies.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTblCompanies.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTblCompanies.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTblCompanies.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTblCompanies.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
}
